import PushNotification from 'react-native-push-notification';
import PushNotificationIOS from 'react-native-push-notification';
import DeviceInfo from 'react-native-device-info';
import { TaharaEventType } from './Chashavshavon/TaharaEvent';
import Utils from './JCal/Utils';
import { log, range } from './GeneralUtils';

export function configureNotifier(onRegister, onNotification) {
    PushNotification.configure({
        // (optional) Called when Token is generated (iOS and Android)
        onRegister: function(token) {
            log('TOKEN:', token);
            if (onRegister) {
                onRegister(token);
            }
        },

        // (required) Called when a remote or local notification is opened or received
        onNotification: async function(notification) {
            log('NOTIFICATION:', notification);
            if (onNotification) {
                onNotification(notification);
            }
            notification.finish(PushNotificationIOS.FetchResult.NoData);
        },
        permissions: {
            alert: true,
            badge: true,
            sound: true,
        },
        popInitialNotification: true,
        requestPermissions: true,
    });
}

/**
 * Adds a system local scheduled notification
 * @param {Number} id
 * @param {String} title
 * @param {String} message
 * @param {Date} date
 */
export function addNotification(id, title, message, date) {
    PushNotification.localNotificationSchedule({
        date,
        message,
        id: id.toString(), // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        userInfo: { id: id.toString() },
        ticker: 'Luach Alarm',
        autoCancel: true,
        largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
        smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: message,
        subText: title,
        //color: "red", // (optional) default: system default
        vibrate: true,
        vibration: 1000,
        //tag: 'some_tag', // (optional) add tag to message
        //group: "group", // (optional) add group to message
        ongoing: false,
        priority: 'high',
        visibility: 'private',
        importance: 'high',
        alertAction: 'view', // (optional) default: view
        category: null, // (optional) default: null
        title: title,
        playSound: true,
        soundName: 'default',
        number: '10',
        //repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
        actions: '[]',
    });
}

/**
 *
 * @param {id:number} id
 */
export function cancelAlarm(id) {
    PushNotification.cancelLocalNotifications({
        id: id.toString(),
    });
}

/**
 *
 * @param {taharaEventId:number} id
 */
export function cancelAllBedikaAndMikvaAlarms(taharaEventId) {
    for (let i of range(20)) {
        try {
            cancelAlarm(`${TaharaEventType.Hefsek}${taharaEventId}${i}`);
        } catch (e) {
            /*Nu, nu*/
        }
    }
}

/**
 * Cancels the "Do a Hefsek" reminder (if available)
 */
export function cancelHefsekTaharaAlarm() {
    try {
        cancelAlarm(TaharaEventType.Hefsek);
    } catch (e) {
        /*Nu, nu*/
    }
}

/**
 *
 * @param {JDate} jdate
 * @param {{hour:Number, minute:Number}} time
 * @param {{hour:Number, minute:Number}} sunset
 * @param  {discreet:Boolean} discreet
 */
export function addHefsekTaharaAlarm(jdate, time, sunset, discreet) {
    const hefsekText = discreet ? 'H.T.' : 'Hefsek Tahara',
        sdate = jdate.getDate();
    sdate.setHours(time.hour, time.minute, 0);

    cancelHefsekTaharaAlarm();
    addNotification(
        TaharaEventType.Hefsek,
        `LUach - ${hefsekText} Reminder`,
        `A  ${hefsekText} may be possible today before shkiah.\nSunset today is at ${Utils.getTimeString(
            sunset,
            DeviceInfo.is24Hour
        )}.`,
        sdate
    );
}
